### ISSUE TITLE
Error when using -B

### ISSUE THREAD

**Issue by lcoombe** [bcgsc/kollector#13]
This is a really minor bug - just thought I'd mention it:

I noticed that when you try to specify the ```-B``` parameter for kollector.sh, you get an error:
```/projects/btl/lcoombe/git/kollector/bin/kollector.sh: illegal option -- B```

I believe that parameter was renamed from ```-a``` at some point, and I think this line just wasn't updated:
```while getopts a:A:d:eg:hH:Cj:k:K:r:s:m:n:o:p: opt; do```
So ```-B``` is just seen as an invalid option.

**Comment by JustinChu** [comment]
I broke it when I made I tried to make it an optional value. Should be fixed now.

**Comment by lcoombe** [comment]
Awesome - thanks Justin!
