### ISSUE TITLE
illegal option -- a

### ISSUE THREAD

**Issue by mikheyev** [bcgsc/kollector#14]
`kollector_multiple.sh` passes a variable `a` to `kollector.sh`, which results in an error:

```
kollector.sh: illegal option -- a
kollector.sh: line 79: OPTARG: unbound variable
srun: error: sango10301: task 0: Exited with exit code 1
```

**Comment by JustinChu** [comment]
Thanks for the report. I've push a fix to the master branch. I'm testing it now.

**Comment by JustinChu** [comment]
My testing seems to indicate it is working with the current revision. Let me know if you have any problems.
Thanks

**Comment by mikheyev** [comment]
Yes it works, thank you!
