### ISSUE TITLE
Coverage Required for Meaningful Assembly

### ISSUE THREAD

**Issue by chocotwig** [bcgsc/kollector#26]
Hi,
I'm wondering -- have you tried subsetting the short-read genomic coverage? At what point do you start to see big drops in contig N50? I'm seeing that you are frequently getting >1000 bp upstream and downstream of the ORF-sequence from your paper. But this is with often > 40x coverage. What do you think happens if the coverage would be lowered to, say, 10x? I'm suspecting that this would still be sufficient to permit local assembly? Do you agree?

**Comment by lcoombe** [comment]
Hello @chocotwig,
Apologies for the very delayed response! I'll still answer in case it'll help others.
While we haven't specifically tested this, I would expect that you would start to see a drop-off in the contiguity once you got to <30X coverage or so. While it is a targeted assembly, for a de Bruijn graph-based approach to work, having a good level of redundancy in the reads is still important to ensure that the 'good' k-mers have sufficient coverage to produce a good assembly. I wouldn't expect the coverage requirement for assembly to change drastically even for targeted assembly.
That being said, if any users have further data about this point, we'd be very interested to see that!
