### ISSUE TITLE
Kollector on 10x Genomics data?

### ISSUE THREAD

**Issue by auesro** [bcgsc/kollector#30]
Hello,

Is it possible to use Kollector with "paired" data from short-read 10x genomics experiments?

Thanks

A

**Comment by lcoombe** [comment]
Hi @auesro,

Yes, you could certainly use paired-end linked reads for Kollector - just note that the pipeline will treat the reads like "normal" short reads, so will not use the barcode information. 
Also note that Kollector expects separate R1/R2 fastq read files - commonly, 10X genomics linked reads will be in a single, interleaved file. If that's true for your reads, you would need to de-interleave that file prior to running Kollector.

Thank you for your interest in Kollector!
Lauren

**Comment by auesro** [comment]
Hi @lcoombe ,

Just to make sure I am on the same page (quite new to assembling datasets), I am referring to 10x 3´ mRNA transcriptomic short paired-end reads. I have never heard the term "linked reads" before associated with this type of experiment so I thought I would mention it.

My 10x reads are in 2 separated, R1, R2 files so no problem there.

Is it still possible to use Kollector in this scenario?

Thanks for your help, Lauren!

Cheers,

A

**Comment by lcoombe** [comment]
Hi @auesro,

Ah, when you mentioned short-read 10X genomics experiments, I assumed you mean chromium genomic linked reads. 

Kollector uses genomic reads to reconstruct gene loci, so it isn't designed to use RNA-seq reads. Part of the reason is that ABySS (the assembler used in Kollector) is a genome assembler, and the progressive Bloom filter used prior to assembly is designed to recruit intronic sequences for a given transcript target.

That being said, if you assembled the transcriptome data (Ex. using RNA-bloom), you could use any of those transcripts with Kollector to reconstruct the underlying gene region if you have matching genomic reads.

Hope that helps!
Lauren

**Comment by auesro** [comment]
Sorry for the confusion, @lcoombe, as I said, I am new to this.

It sounds interesting cause my experiment was with nuclear mRNA, so introns should be there mostly?

My idea was to use Kollector to pick up the transgene sequence of the mouse line used in the experiment: it contains a GFP sequence but I have no idea about what is 3' of the CDS, so the idea was to reconstruct it from the reads in order to add it to the reference mouse genome annotation file so that I could quantify its expression in my cells... nuclei in this case (as you might know the 3' 10x tech mostly only gets to sequence the 3'UTR and, if it is long enough, very little from the CDS).

Does it make any sense?

Thanks for your help!

A

**Comment by lcoombe** [comment]
Hi @auesro,

I see - but even if the data was nuclear, wouldn't you still expect some mix of pre- and post-processed mRNAs? 

We've only tested Kollector using genomic reads, so I can't really make any guarantees for how it would work on RNAseq data. If the intent was to start with your target GFP sequence and recruit reads up/downstream, you could use the progessive Bloom filter part of Kollector, but I don't think ABySS would be appropriate. ABySS is a de novo genome assembler, not a transcriptome assembler.

Perhaps you could use the progressive Bloom filter to recruit reads, then assembly with RNA-bloom? @kmnip do you have any thoughts?

**Comment by kmnip** [comment]
Are these are UMI-based single-cell RNA-seq reads from 10x?
You need to check whether both reads contain sequences of the 3'UTR. If so, then you can trim off the barcode sequences. However, I think the left reads only contain the barcodes/UMI and the right reads contain the UTR.

**Comment by auesro** [comment]
Hi both Laura and Ka,

Thanks for your help, as I said I am very new to all this.

@lcoombe how would you go about using only the Bloom filter part of Kollector to recruit the relevant reads? I have the CDS sequences of my transgenes (sfGFP and Bgal) so I need specially the 3'UTRs for both. What command should I use in this scenario?

Yes, @kmnip is right. They are 10x UMI-based single NUCLEI RNAseq reads (so I will have both intron and exon reads but given I am only searching for the transgenes they will both be made of only exonic reads). Indeed, the left reads only contain the UMI and cell (nuclei in my case) barcodes, I didnt think of that. It will probably be best to just provide RNA-bloom with the right (R2) reads, correct? I have already trimmed both sets of reads for illumina sequences plus a leftover sequence from the library construction in the R2 reads but I did not remove the possible barcodes located at the 3' (left) of the R2 reads (which are 88 bases long originally, 58 after the removal of the leftover sequence).

**Comment by kmnip** [comment]
You can trim the UMIs and cell barcodes with `umitools extract`:
https://umi-tools.readthedocs.io/en/latest/Single_cell_tutorial.html
https://umi-tools.readthedocs.io/en/latest/reference/extract.html

Are you trying to assemble the 3'UTR for each cell individually or together?

**Comment by auesro** [comment]
Thanks for the umitools suggestion.

I dont care about if for each cell individually or together, whatever works best: since its a transgene with no introns I expect it should be the same mRNA in each cell.

Any suggestions?

**Comment by kmnip** [comment]
Yes, please open a new issue in RNA-Bloom and discuss it there.
Thanks,
Ka Ming

**Comment by auesro** [comment]
[Done!](https://github.com/bcgsc/RNA-Bloom/issues/34#issue-1121244548)
Thanks!
A
