### ISSUE TITLE
Kollector fails for full path to transcript file

### ISSUE THREAD

**Issue by arvestad** [bcgsc/kollector#5]
I played around with kollector and set up a run for which I gave a full path to the data:
```
kollector.sh /home/me/data/transcripts.fa /home/me/data/reads1.fq /home/me/data/reads2.fq
```

Recruitment of reads works, and most of the assembly also seems to work (there is data in kollector-8.fa), but it fails in a late step. The error message is:
```
Command exited with non-zero status 2
=> kollector.sh: 0.78 abyss-pe -C kollector.abyss v=-v k=32 name=kollector np=1 lib=pet pet=../kollector.recruited_pe.fastq long=longlib longlib=..//home/me/data/transcripts.fa
```

It seems that path for the longlib parameter is prepended with "..", in belief it is a relative path.

**Comment by erdikucuk** [comment]
Hi,
Thanks for reporting the issue. See the following commit that fixes it: 2c586c6f6d4500227591cdcc55f6ac1aadf3152b
