### ISSUE TITLE
Errors in kollector_multiple.sh

### ISSUE THREAD

**Issue by KristinaGagalova** [bcgsc/kollector#8]
1) Line 122: kollector (abyss step) cannot find prevfailed.fa during the bwa. prevfailed.fa needs to be added as absolute path here

```
seed_new="$(pwd)"/prevfailed.fa
kollector.sh -j$j -d$d -k$k -K$K -r$newr -s$s -p$p -n$n -o$o -a$a $seed_new $pet1 $pet2
``` 
2) Line 124: missing succeedtranscripts.txt. Loop fails. 
Add:
```
cut -f1 -d " " hitlist.txt|sort|uniq > succeedtranscripts.txt
```
3) Line 109 and 122:
kollector is called in the wrong way. Correct order if first the options and than $seed, $pet1, $pet2.     
This is the correct order:
```
Usage: $PROGRAM [options] <seed> <pet_read1.fq> <pet_read2.fq> 
``` 
Line 109 has also an extra *p* parameter

**Comment by JustinChu** [comment]
Were these fixes included in the https://github.com/bcgsc/kollector/tree/develop branch?

**Comment by KristinaGagalova** [comment]
yep, the working version is on the dev branch
